name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_analyze:
    name: Build, Analyze and Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for accurate analysis

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle  # Enable automatic Gradle caching

      - name: Cache SonarQube packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-${{ hashFiles('**/*.gradle', '**/sonar-project.properties') }}
          restore-keys: |
            ${{ runner.os }}-sonar-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build and Test
        run: ./gradlew build test --info

      - name: SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_TICKET_LOG_BACKEND }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL_TICKET_LOG_BACKEND }}
        run: ./gradlew sonarqube --info -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY_TICKET_LOG_BACKEND }} -Dsonar.projectName=${{ secrets.SONAR_PROJECT_NAME_TICKET_LOG_BACKEND }}
